import streamlit as st
from firecrawl import Firecrawl
from google import genai
from fpdf import FPDF

# --- 1. CONFIGURACIÓN DE PÁGINA ---
st.set_page_config(
    page_title="NEXUS SEO Pro",
    page_icon="⚡",
    layout="wide"
)

# --- 2. SEGURIDAD: CONTROL DE ACCESO ---
def verificar_password():
    if "autenticado" not in st.session_state:
        st.session_state["autenticado"] = False

    if not st.session_state["autenticado"]:
        col1, col2, col3 = st.columns([1, 2, 1])
        with col2:
            st.title("🔐 Acceso NEXUS Pro")
            password_input = st.text_input("Código de Licencia / License Key:", type="password")
            if st.button("Activar / Activate"):
                if password_input == "NEXUS2025":
                    st.session_state["autenticado"] = True
                    st.rerun()
                else:
                    st.error("Código inválido / Invalid Key")
        return False
    return True

# --- 3. CARGA DE SECRETOS ---
try:
    KEY_FIRECRAWL = st.secrets["FIRE_KEY"]
    KEY_GOOGLE = st.secrets["GEMINI_KEY"]
except Exception:
    st.error("Configura FIRE_KEY y GEMINI_KEY en los Secrets de Streamlit.")
    st.stop()

# --- 4. FUNCIÓN: GENERADOR DE PDF PROFESIONAL ---
def crear_pdf(texto_reporte, url_analizada, score, lang):
    pdf = FPDF()
    pdf.add_page()
    
    # Textos dinámicos según idioma
    titulo_doc = "NEXUS SEO REPORT" if lang == "English" else "REPORTE SEO NEXUS"
    sub_url = f"Analysis for: {url_analizada}" if lang == "English" else f"Análisis para: {url_analizada}"
    score_label = "SEO Health Score" if lang == "English" else "Puntuación de Salud SEO"
    footer_text = "Generated by NEXUS Pro - Strategic Audit Report" if lang == "English" else "Generado por NEXUS Pro - Reporte de Auditoría Estratégica"

    # Encabezado
    pdf.set_font("Arial", 'B', 20)
    pdf.set_text_color(255, 75, 75) 
    pdf.cell(0, 15, titulo_doc, ln=True, align='C')
    
    pdf.set_font("Arial", 'B', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, sub_url, ln=True, align='C')
    pdf.cell(0, 10, f"{score_label}: {score}/100", ln=True, align='C')
    pdf.ln(10)
    
    # Cuerpo del reporte
    pdf.set_font("Arial", size=11)
    texto_limpio = texto_reporte.replace("**", "").replace("#", "").replace("`", "").replace("•", "-")
    
    try:
        pdf.multi_cell(0, 8, texto_limpio.encode('latin-1', 'replace').decode('latin-1'))
    except Exception:
        pdf.multi_cell(0, 8, texto_limpio.replace("—", "-")) # Fallback simple
    
    # Pie de página
    pdf.set_y(-20)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, footer_text, align='C')
    
    return bytes(pdf.output(dest='S'))

# --- 5. LÓGICA DEL AGENTE ---
def ejecutar_auditoria(url, lang):
    try:
        app = Firecrawl(api_key=KEY_FIRECRAWL)
        client = genai.Client(api_key=KEY_GOOGLE)
    except Exception as e:
        return f"Error: {e}", 0

    with st.status("🕵️‍♂️ NEXUS Pro Processing...", expanded=True) as status:
        st.write("👀 Reading web content...")
        try:
            scrape = app.scrape(url)
            contenido = scrape.markdown if hasattr(scrape, 'markdown') else str(scrape)
        except Exception as e:
            return f"Error: {e}", 0

        st.write(f"🧠 Generating Strategy in {lang}...")
        prompt = f"""
        Act as NEXUS Pro, a senior SEO consultant. Analyze this site: {url}
        LANGUAGE: All your response must be in {lang}.
        
        INSTRUCTIONS:
        1. Start with: "SCORE: [Number 0-100]"
        2. Provide: 3 Critical SEO Errors, 3 H1 Suggestions, and a Copywriting Rewrite for conversion.
        Content to analyze: {contenido[:15000]}
        """
        
        modelos = ["gemini-2.0-flash-exp", "gemini-1.5-pro"]
        resultado = None
        
        for mod in modelos:
            try:
                st.write(f"🔌 Connecting to: {mod}...")
                response = client.models.generate_content(model=mod, contents=prompt)
                resultado = response.text
                if resultado: break
            except: continue
        
        if resultado:
            status.update(label="✅ Analysis Complete", state="complete")
            try:
                score_val = int(resultado.split("SCORE:")[1].split("\n")[0].replace("[","").replace("]","").strip())
            except: score_val = 65
            return resultado, score_val
        else:
            return "Error: Engines busy.", 0

# --- 6. INTERFAZ DE USUARIO ---
if verificar_password():
    # Sidebar
    st.sidebar.title("⚡ NEXUS Pro")
    idioma = st.sidebar.selectbox("Idioma del Reporte / Language", ["Español", "English"])
    
    st.sidebar.markdown("---")
    if st.sidebar.button("Cerrar Sesión / Logout"):
        st.session_state["autenticado"] = False
        st.rerun()

    # Main UI
    st.title("⚡ NEXUS SEO Agent Pro")
    st.markdown("### Agency-level audit reports powered by advanced logic.")

    url_input = st.text_input("URL:", placeholder="https://example.com")

    if st.button("🚀 START AUDIT") and url_input:
        reporte, score = ejecutar_auditoria(url_input, idioma)
        
        if "Error" in reporte and len(reporte) < 150:
            st.error(reporte)
        else:
            st.balloons()
            st.divider()
            
            # Score Metrics
            c1, c2 = st.columns([1, 2])
            with c1:
                st.metric("Health Score", f"{score}/100")
                st.progress(score / 100)
                
            with c2:
                if score < 50: st.error("Urgent SEO improvements needed.")
                elif score < 85: st.warning("Optimization opportunities detected.")
                else: st.success("Well-optimized site.")

            st.markdown("### 📝 Detailed Report")
            st.info(reporte)

            # PDF Download
            try:
                pdf_bytes = crear_pdf(reporte, url_input, score, idioma)
                st.download_button(
                    label=f"📩 Download PDF ({idioma})",
                    data=pdf_bytes,
                    file_name=f"Audit_NEXUS_{url_input.replace('https://','').replace('.','_')}.pdf",
                    mime="application/pdf"
                )
            except Exception as e:
                st.error(f"PDF Error: {e}")
