import streamlit as st
from firecrawl import Firecrawl
from google import genai
from fpdf import FPDF

# --- 1. CONFIGURACIÓN DE PÁGINA ---
st.set_page_config(
    page_title="NEXUS SEO Pro",
    page_icon="⚡",
    layout="wide"
)

# --- 2. SEGURIDAD: CONTROL DE ACCESO ---
def verificar_password():
    if "autenticado" not in st.session_state:
        st.session_state["autenticado"] = False

    if not st.session_state["autenticado"]:
        col1, col2, col3 = st.columns([1, 2, 1])
        with col2:
            st.title("🔐 Acceso NEXUS Pro")
            password_input = st.text_input("License Key / Código de Licencia:", type="password")
            if st.button("Activate / Activar"):
                if password_input == "NEXUS2025":
                    st.session_state["autenticado"] = True
                    st.rerun()
                else:
                    st.error("Invalid Key / Código Inválido")
        return False
    return True

# --- 3. CARGA DE SECRETOS ---
try:
    KEY_FIRECRAWL = st.secrets["FIRE_KEY"]
    KEY_GOOGLE = st.secrets["GEMINI_KEY"]
except Exception:
    st.error("Configura FIRE_KEY y GEMINI_KEY en los Secrets de Streamlit.")
    st.stop()

# --- 4. FUNCIÓN: GENERADOR DE PDF MULTI-IDIOMA ---
def crear_pdf(texto_reporte, url_analizada, score, lang):
    pdf = FPDF()
    pdf.add_page()
    
    # Diccionario de traducciones para encabezados del PDF
    traducciones = {
        "English": {"titulo": "NEXUS SEO REPORT", "sub": "Analysis for:", "score": "SEO Health Score", "footer": "Generated by NEXUS Pro"},
        "Español": {"titulo": "REPORTE SEO NEXUS", "sub": "Análisis para:", "score": "Puntuación de Salud SEO", "footer": "Generado por NEXUS Pro"},
        "German": {"titulo": "NEXUS SEO-BERICHT", "sub": "Analyse für:", "score": "SEO-Gesundheitswert", "footer": "Erstellt von NEXUS Pro"},
        "Portugues": {"titulo": "RELATÓRIO SEO NEXUS", "sub": "Análise para:", "score": "Pontuação de Saúde SEO", "footer": "Gerado por NEXUS Pro"},
        "Dutch": {"titulo": "NEXUS SEO-RAPPORT", "sub": "Analyse voor:", "score": "SEO-gezondheidsscore", "footer": "Gegenereerd door NEXUS Pro"},
        "Italian": {"titulo": "RAPPORTO SEO NEXUS", "sub": "Analisi per:", "score": "Punteggio Salute SEO", "footer": "Generato da NEXUS Pro"},
        "Arabic": {"titulo": "NEXUS SEO REPORT", "sub": "Analysis for:", "score": "SEO Score", "footer": "Generated by NEXUS Pro"}
    }
    
    t = traducciones.get(lang, traducciones["English"])

    # Encabezado
    pdf.set_font("Arial", 'B', 20)
    pdf.set_text_color(255, 75, 75) 
    pdf.cell(0, 15, t["titulo"], ln=True, align='C')
    
    pdf.set_font("Arial", 'B', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, f"{t['sub']} {url_analizada}", ln=True, align='C')
    pdf.cell(0, 10, f"{t['score']}: {score}/100", ln=True, align='C')
    pdf.ln(10)
    
    # Cuerpo del reporte
    pdf.set_font("Arial", size=11)
    # Limpieza de caracteres para compatibilidad Latin-1
    texto_limpio = texto_reporte.replace("**", "").replace("#", "").replace("`", "").replace("•", "-")
    
    try:
        # Nota: El árabe estándar en FPDF requiere fuentes Unicode específicas. 
        # Para esta versión mantenemos Arial/Latin-1; si el reporte es en árabe, la IA usará caracteres compatibles o transliteración.
        pdf.multi_cell(0, 8, texto_limpio.encode('latin-1', 'replace').decode('latin-1'))
    except Exception:
        pdf.multi_cell(0, 8, texto_limpio)
    
    # Pie de página
    pdf.set_y(-20)
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, t["footer"], align='C')
    
    return bytes(pdf.output(dest='S'))

# --- 5. LÓGICA DEL AGENTE ---
def ejecutar_auditoria(url, lang):
    try:
        app = Firecrawl(api_key=KEY_FIRECRAWL)
        client = genai.Client(api_key=KEY_GOOGLE)
    except Exception as e:
        return f"Error: {e}", 0

    with st.status(f"🕵️‍♂️ NEXUS Pro: {lang} Analysis...", expanded=True) as status:
        st.write("👀 Reading web content...")
        try:
            scrape = app.scrape(url)
            contenido = scrape.markdown if hasattr(scrape, 'markdown') else str(scrape)
        except Exception as e:
            return f"Error: {e}", 0

        st.write(f"🧠 Generating Intelligence in {lang}...")
        prompt = f"""
        Act as NEXUS Pro, a senior SEO consultant. Analyze this site: {url}
        LANGUAGE: All your response MUST be in {lang}.
        
        INSTRUCTIONS:
        1. Start with: "SCORE: [Number 0-100]"
        2. Provide: 3 Critical SEO Errors, 3 H1 Suggestions, and a Copywriting Rewrite for conversion.
        Content: {contenido[:15000]}
        """
        
        modelos = ["gemini-2.0-flash-exp", "gemini-1.5-pro"]
        resultado = None
        
        for mod in modelos:
            try:
                st.write(f"🔌 Using Engine: {mod}...")
                response = client.models.generate_content(model=mod, contents=prompt)
                resultado = response.text
                if resultado: break
            except: continue
        
        if resultado:
            status.update(label="✅ Success", state="complete")
            try:
                score_val = int(resultado.split("SCORE:")[1].split("\n")[0].replace("[","").replace("]","").strip())
            except: score_val = 65
            return resultado, score_val
        else:
            return "Error: System Busy.", 0

# --- 6. INTERFAZ DE USUARIO ---
if verificar_password():
    # Sidebar
    st.sidebar.title("⚡ NEXUS Pro")
    idioma = st.sidebar.selectbox(
        "Select Language / Idioma", 
        ["English", "Español", "German", "Portugues", "Dutch", "Italian", "Arabic"]
    )
    
    st.sidebar.markdown("---")
    if st.sidebar.button("Logout / Cerrar Sesión"):
        st.session_state["autenticado"] = False
        st.rerun()

    # Main UI
    st.title("⚡ NEXUS SEO Agent Pro")
    st.markdown(f"### Global Audit Interface | Language: **{idioma}**")

    url_input = st.text_input("URL:", placeholder="https://example.com")

    if st.button("🚀 RUN AUDIT") and url_input:
        reporte, score = ejecutar_auditoria(url_input, idioma)
        
        if "Error" in reporte and len(reporte) < 150:
            st.error(reporte)
        else:
            st.balloons()
            st.divider()
            
            c1, c2 = st.columns([1, 2])
            with c1:
                st.metric("SEO Score", f"{score}/100")
                st.progress(score / 100)
                
            with c2:
                st.markdown("#### Analysis Insight")
                if score < 50: st.error("Critical: Immediate action required.")
                elif score < 85: st.warning("Notice: Optimization opportunities available.")
                else: st.success("Excellent: High optimization level.")

            st.markdown("### 📝 Detailed Intelligence")
            st.info(reporte)

            # PDF Download
            try:
                pdf_bytes = crear_pdf(reporte, url_input, score, idioma)
                st.download_button(
                    label=f"📩 Download {idioma} PDF Report",
                    data=pdf_bytes,
                    file_name=f"NEXUS_Audit_{idioma}_{url_input.replace('https://','').replace('.','_')}.pdf",
                    mime="application/pdf"
                )
            except Exception as e:
                st.error(f"PDF Generation Error: {e}")
